import type { WordItem, WordModule } from '../types'

export const wordBank: WordItem[] = [
  {
    text: 'thank you',
    difficulty: 'Beginner',
    module: 'words',
    syllables: ['thank', 'you'],
    tips: ['Feel the tongue touch the upper teeth for “th”.', 'Slow down between syllables.'],
  },
  {
    text: 'river',
    difficulty: 'Beginner',
    module: 'words',
    syllables: ['ri', 'ver'],
    tips: ['Keep the R sound relaxed.', 'Smile slightly for the “v” sound.'],
  },
  {
    text: 'good morning',
    difficulty: 'Beginner',
    module: 'words',
    syllables: ['good', 'morn', 'ing'],
    tips: ['Make the “g” sound soft at the end.', 'Pause slightly between words.'],
  },
  {
    text: 'coffee',
    difficulty: 'Beginner',
    module: 'words',
    syllables: ['cof', 'fee'],
    tips: ['Round your lips for the “cof”.', 'Keep the second syllable short.'],
  },
  {
    text: 'meeting',
    difficulty: 'Beginner',
    module: 'words',
    syllables: ['meet', 'ing'],
    tips: ['Stretch the “ee” sound.', 'Drop the “g” softly if it helps.'],
  },
  {
    text: '51',
    difficulty: 'Beginner',
    module: 'numbers',
    numeralCategory: 'cardinal',
    syllables: ['fif', 'ty', 'one'],
    tips: ['Keep the "f" sounds clear.', 'Pause between words.'],
  },
  {
    text: 'room 305',
    difficulty: 'Beginner',
    module: 'mix',
    numeralCategory: 'nominal',
    syllables: ['room', 'three', 'oh', 'five'],
    tips: ['Round your lips for “room”.', 'Push air on “three”.'],
  },
  {
    text: 'call me at 8',
    difficulty: 'Beginner',
    module: 'mix',
    numeralCategory: 'cardinal',
    syllables: ['call', 'me', 'at', 'eight'],
    tips: ['Open the mouth for “call”.', 'Make a long smooth “eight”.'],
  },
  {
    text: '2',
    difficulty: 'Beginner',
    module: 'numbers',
    numeralCategory: 'cardinal',
    syllables: ['two'],
    tips: ['Round your lips for the "oo" sound.'],
  },
  {
    text: '42',
    difficulty: 'Beginner',
    module: 'numbers',
    numeralCategory: 'cardinal',
    syllables: ['for', 'ty', 'two'],
    tips: ['Stress the "for".', 'Keep the "ty" short.'],
  },
  {
    text: '73',
    difficulty: 'Beginner',
    module: 'numbers',
    numeralCategory: 'cardinal',
    syllables: ['sev', 'en', 'ty', 'three'],
    tips: ['Tongue between teeth for "th".', 'Smile for the "v".'],
  },
  {
    text: '2513',
    difficulty: 'Intermediate',
    module: 'numbers',
    numeralCategory: 'cardinal',
    syllables: ['two', 'thou', 'sand', 'five', 'hun', 'dred', 'and', 'thir', 'teen'],
    tips: ['Pace yourself through the sequence.', 'Tongue between teeth for "th".'],
  },
  {
    text: '1 or 2',
    difficulty: 'Beginner',
    module: 'numbers',
    numeralCategory: 'multiplicative',
    syllables: ['once', 'or', 'twice'],
    tips: ['Make the “w” in “twice” smooth.', 'Keep a small pause before “twice”.'],
  },
  {
    text: 'wonderful',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['won', 'der', 'ful'],
    tips: ['Hold the “der” syllable longer.', 'Keep breath steady.'],
  },
  {
    text: 'wonderful',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['won', 'der', 'ful'],
    tips: ['Hold the “der” syllable longer.', 'Keep breath steady.'],
  },
  {
    text: 'enthusiasm',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['en', 'thu', 'si', 'asm'],
    tips: ['Push air for the “th”.', 'Avoid merging “si” and “asm”.'],
  },
  {
    text: 'accept',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['ac', 'cept'],
    tips: ['Stress the second syllable.', 'Make the "pt" sounds clear at the end.'],
  },
  {
    text: 'achieve',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['a', 'chieve'],
    tips: ['Make the "ch" sound sharp.', 'Stretch the "ee" sound gently.'],
  },
  {
    text: 'advice',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['ad', 'vice'],
    tips: ['Let the "s" sound in "vice" ring slightly.', 'Keep the "a" light.'],
  },
  {
    text: 'allow',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['al', 'low'],
    tips: ['Open your mouth wide for the "ow" sound as in "now".'],
  },
  {
    text: 'appear',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['ap', 'pear'],
    tips: ['Pop your lips slightly for the "p".', 'Keep the "ear" sound clear and soft.'],
  },
  {
    text: 'apply',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['ap', 'ply'],
    tips: ['Pop the "p" cleanly.', 'End with a long "eye" sound.'],
  },
  {
    text: 'arrange',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['ar', 'range'],
    tips: ['Make a soft "j" sound for the "ge" at the end.', 'Keep the "R" sound relaxed.'],
  },
  {
    text: 'avoid',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['a', 'void'],
    tips: ['Carefully say the "voy" sound.', 'Hit the "d" ending gently.'],
  },
  {
    text: 'believe',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['be', 'lieve'],
    tips: ['Stress the second syllable.', 'Extend the "ee" sound smoothly.'],
  },
  {
    text: 'belong',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['be', 'long'],
    tips: ['Let the "ng" sound vibrate lightly in your nose.', 'Stress "long".'],
  },
  {
    text: 'borrow',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['bor', 'row'],
    tips: ['Make the first syllable sound like "bore".', 'Round your lips for the "o".'],
  },
  {
    text: 'possible',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['pos', 'si', 'ble'],
    tips: ['Keep the "s" sound clear.', 'Make the "ble" ending soft.'],
  },
  {
    text: 'powerful',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['pow', 'er', 'ful'],
    tips: ['Start with a strong "pow".', 'Keep the "ful" ending gentle.'],
  },
  {
    text: 'quiet',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['qui', 'et'],
    tips: ['Start with a sharp "kw" sound.', 'Make the "et" short and soft.'],
  },
  {
    text: 'responsible',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['re', 'spon', 'si', 'ble'],
    tips: ['Emphasize the "spon" syllable.', 'Keep the "r" relaxed.'],
  },
  {
    text: 'successful',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['suc', 'cess', 'ful'],
    tips: ['Make sure the first "c" sounds like "k" and second like "s".', 'Stress the "cess" syllable.'],
  },
  {
    text: 'useful',
    difficulty: 'Intermediate',
    module: 'words',
    syllables: ['use', 'ful'],
    tips: ['Make the "u" sound like "you".', 'Keep the "s" sounding like "s", not "z".'],
  },
  {
    text: 'entrepreneurship',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['en', 'tre', 'pre', 'neur', 'ship'],
    tips: ['Stress “neur” with clarity.', 'Keep syllables even.'],
  },
  {
    text: 'responsibility',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['re', 'spon', 'si', 'bil', 'i', 'ty'],
    tips: ['Break the word into smaller chunks.', 'Emphasize “spon”.'],
  },
  {
    text: 'ubiquitous',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['u', 'biq', 'ui', 'tous'],
    tips: ['Start with a "you" sound.', 'Stress the "biq" syllable.'],
    meaning: 'Something is ubiquitous when you can see it everywhere.',
  },
  {
    text: 'obfuscate',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['ob', 'fus', 'cate'],
    tips: ['Stress the "fus" syllable.'],
    meaning: 'To obfuscate means to make something confusing so people cannot understand it easily.',
  },
  {
    text: 'ephemeral',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['e', 'phem', 'er', 'al'],
    tips: ['The "ph" makes an "f" sound.', 'Stress the "phem" syllable.'],
    meaning: 'Something is ephemeral when it lasts only a short time.',
  },
  {
    text: 'magnanimous',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['mag', 'nan', 'i', 'mous'],
    tips: ['Stress the "nan" syllable.'],
    meaning: 'A magnanimous person is very kind and forgives others easily.',
  },
  {
    text: 'esoteric',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['es', 'o', 'ter', 'ic'],
    tips: ['Stress the "ter" syllable.'],
    meaning: 'Something is esoteric when only a small group of people understand it.',
  },
  {
    text: 'meticulous',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['me', 'tic', 'u', 'lous'],
    tips: ['Stress the "tic" syllable.'],
    meaning: 'A meticulous person checks every small detail carefully.',
  },
  {
    text: 'tenacious',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['te', 'na', 'cious'],
    tips: ['The "cious" sounds like "shus".', 'Stress the "na" syllable.'],
    meaning: 'A tenacious person keeps trying and does not give up.',
  },
  {
    text: 'ambivalent',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['am', 'biv', 'a', 'lent'],
    tips: ['Stress the "biv" syllable.'],
    meaning: 'When you are ambivalent, you have mixed feelings and cannot decide.',
  },
  {
    text: 'ostentatious',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['os', 'ten', 'ta', 'tious'],
    tips: ['The "tious" sounds like "shus".', 'Stress the "ta" syllable.'],
    meaning: 'Something is ostentatious when someone shows off their wealth or things to impress others.',
  },
  {
    text: 'impeccable',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['im', 'pec', 'ca', 'ble'],
    tips: ['Stress the "pec" syllable.'],
    meaning: 'Something is impeccable when it is perfect and has no mistakes.',
  },
  {
    text: 'ineffable',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['in', 'ef', 'fa', 'ble'],
    tips: ['Stress the "ef" syllable.'],
    meaning: 'Something is ineffable when it is so amazing that it is hard to describe in words.',
  },
  {
    text: 'pragmatic',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['prag', 'mat', 'ic'],
    tips: ['Stress the "mat" syllable.'],
    meaning: 'A pragmatic person thinks in a practical and realistic way.',
  },
  {
    text: 'resilient',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['re', 'sil', 'i', 'ent'],
    tips: ['The "s" sounds like a "z".', 'Stress the "sil" syllable.'],
    meaning: 'A resilient person can recover quickly after problems or difficulties.',
  },
  {
    text: 'scrutinize',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['scru', 'ti', 'nize'],
    tips: ['Stress the "scru" syllable.'],
    meaning: 'To scrutinize means to look at something very carefully to find details or mistakes.',
  },
  {
    text: 'substantiate',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['sub', 'stan', 'ti', 'ate'],
    tips: ['Stress the "stan" syllable.'],
    meaning: 'To substantiate means to show proof that something is true.',
  },
  {
    text: 'juxtapose',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['jux', 'ta', 'pose'],
    tips: ['Stress the "jux" syllable.', 'The "pose" ends with a "z" sound.'],
    meaning: 'To juxtapose means to put two things next to each other to compare them.',
  },
  {
    text: 'pernicious',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['per', 'ni', 'cious'],
    tips: ['The "cious" sounds like "shus".', 'Stress the "ni" syllable.'],
    meaning: 'Something is pernicious when it slowly causes serious harm.',
  },
  {
    text: 'sagacious',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['sa', 'ga', 'cious'],
    tips: ['The "cious" sounds like "shus".', 'Stress the "ga" syllable.'],
    meaning: 'A sagacious person is very wise and makes good decisions.',
  },
  {
    text: 'trepidation',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['trep', 'i', 'da', 'tion'],
    tips: ['Stress the "da" syllable.'],
    meaning: 'Trepidation is the feeling of fear or worry about something that may happen.',
  },
  {
    text: 'quintessential',
    difficulty: 'Advanced',
    module: 'words',
    syllables: ['quin', 'tes', 'sen', 'tial'],
    tips: ['The "tial" sounds like "shul".', 'Stress the "sen" syllable.'],
    meaning: 'Something is quintessential when it is the perfect example of something.',
  },
  {
    text: '54',
    difficulty: 'Beginner',
    module: 'numbers',
    numeralCategory: 'cardinal',
    syllables: ['fif', 'ty', 'four'],
    tips: ['Clear "f" sounds.', 'Stress the first syllable "fif".'],
  },
  {
    text: '75',
    difficulty: 'Beginner',
    module: 'numbers',
    numeralCategory: 'cardinal',
    syllables: ['sev', 'en', 'ty', 'five'],
    tips: ['Smile for the "v" sound.', 'Gentle "y" ending.'],
  },
  {
    text: '6',
    difficulty: 'Beginner',
    module: 'numbers',
    numeralCategory: 'cardinal',
    syllables: ['six'],
    tips: ['Sharp "s" and "x" sounds.', 'Keep it short.'],
  },
  {
    text: '1275',
    difficulty: 'Intermediate',
    module: 'numbers',
    numeralCategory: 'cardinal',
    syllables: ['one', 'thou', 'sand', 'two', 'hun', 'dred', 'and', 'sev', 'en', 'ty', 'five'],
    tips: ['Tongue between teeth for "th".', 'Pace yourself through the long sequence.'],
  },
]

export const getWordsByLevel = (level: WordItem['difficulty'], module?: WordModule) =>
  wordBank.filter(
    (word) => word.difficulty === level && (module ? word.module === module : true),
  )
